### ISSUE TITLE
Valid component missed

### ISSUE THREAD

**Issue by IstuntmanI** [Open-GTO/sa-mp-fixes#10]
FIXES_gscVehicleMods array misses component ID 1001 ("Win" Spoiler) for vehicle ID 585 ("Emperor").

Probably there are even more missed components, but this is the first one a player reported that it is kicking him.

**Comment by ziggi** [comment]
It's bad. I will try to import data from [MTA](https://github.com/multitheftauto/mtasa-blue/blob/master/Server/mods/deathmatch/logic/CVehicleUpgrades.cpp).

**Comment by ziggi** [comment]
> I will try to import data from MTA.

No, it's bad idea, because MTA have more types and slots.

Anyway - fixed, closed, thanks for reporting.
