### ISSUE TITLE
Modshop fix (when certain players collide each other in one modshop)

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/sa-mp-fixes#108]
How about adding something like this?
https://forum.sa-mp.com/showthread.php?t=520391

**Comment by NexiusTailer** [comment]
Ah it seems I didn't find another similar issue that has been made before.
It is related to #53

**Comment by NexiusTailer** [comment]
So what about that fix being merged? :)

**Comment by Y-Less** [comment]
Could do.
