### ISSUE TITLE
Максимальное валидное место для автобуса (ID 431)

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/sa-mp-fixes#11]
Опять проблема с валидными местами, только на этот раз уже проблема частично кроется и в самой игре/мультиплеере:
При попытке посадить игрока в транспорт с идом 431 (автобус) на пассажирское место, игрок на него сядет, но при условии, что место будет 8 и меньше. Тем не менее, как только он на него сел, клиент начинает возвращать ид места 1 независимо от того, на каком пассажирском месте он сидит на самом деле.

**Comment by ziggi** [comment]
А что возвращает, если игрок сам сядет на пассажирское (через G)?

**Comment by NexiusTailer** [comment]
Также 1 вернёт (если сесть как одному игроку, так и двум, трём и т.д...) для каждого

**Comment by ziggi** [comment]
Да уж, слишком геморно исправлять, лень)
