### ISSUE TITLE
SetVehicleZAngle works only for the last interacting player (requires Pawn.RakNet plugin to fix)

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/sa-mp-fixes#117]
SetVehicleZAngle sends player RPC only for the last player who interacted with the vehicle (a player who was the last driver, for example), even after his disconnection. Thus if I enter a car, drive it for some time and then leave the game, the server will send actual "SetVehicleZAngle" RPC to invalid player slot or to the player who entered the same player slot after my disconnection (but in this case he probably will be out of stream of that vehicle).

The same actually with SetVehicleVelocity, but this function doesn't work without driver so the problem can't be reproduced with it in the real case.

**Comment by Y-Less** [comment]
Do you have an idea to fix that without a plugin?

**Comment by NexiusTailer** [comment]
Only with Pawn.RakNet/YSF, unfortunately.

**Comment by Y-Less** [comment]
I have considered making Pawn.RakNet an optional requirement to fix some more things.  But then there's open.mp to fix them better, so....

**Comment by NexiusTailer** [comment]
No one names the exact release dates for this mp and if in the near future it's also unlikely, then it makes sense to include a fix in the current include, which would be useful here and now.

**Comment by NexiusTailer** [comment]
As far as I've noticed it didn't use any other third-party plugins like YSF or Pawn.RakNet even as an optional dependencies for now and if it's some kind of the include policy I can close this issue and issue #110 (as they both related to third-party plugin based solutions) so as not to litter the list of issues with those that aren't planned for implementation here (but maybe it'll be more appropriate for some other projects?).

**Comment by Y-Less** [comment]
I meant it doesn't use them currently, but can do.  There's no reason not to, as long as it it optional.

**Comment by NexiusTailer** [comment]
Okay, no problem then.

P.s. I think it would better to prefer Pawn.RakNet as an optional dependency to solve current and any other similar issues in future as this plugin (unlike the rest like YSF) provides more powerful features and gives more freedom to fix even the most complicated sync issues.

**Comment by Y-Less** [comment]
I entirely agree.
