### ISSUE TITLE
Add check for MAX_PLAYERS and console variable maxplayers

### ISSUE THREAD

**Issue by WoutProvost** [Open-GTO/sa-mp-fixes#131]
These should match. The check should throw an error if they differ.

One of these natives can be used:
```
GetConsoleVarAsInt("maxplayers");
GetMaxPlayers();
```

**Comment by Mergevos** [comment]
@WoutProvost wasn't this fixed in 8fb5ad1280c1003bda89df4d9072204b738ad051 and in cd0834187b35ab60ae24c06539687cbb7348495a?

**Comment by Y-Less** [comment]
Yes it was, thanks.
