### ISSUE TITLE
weaponslot parameter in SetPlayerAmmo

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/sa-mp-fixes#135]
SetPlayerAmmo has a parameter named weaponslot, but it's actually weaponid. Could be redefined.

**Comment by Mergevos** [comment]
@Y-Less this been fixes in stdlib https://github.com/pawn-lang/samp-stdlib/commit/c69f1cbb0a961e3155e8bc29d8c57db855c30d2d

**Comment by Y-Less** [comment]
I know, I merged the PR...

**Comment by Y-Less** [comment]
But a new one here would be good.
