### ISSUE TITLE
VehicleParameters

### ISSUE THREAD

**Issue by mbicanic96** [Open-GTO/sa-mp-fixes#151]
When compiling gamemode after transfering from '13 to '21 fixes.include next warnings pop-up.
It is only on **GetVehicleParamsEx** and **SetVehicleParamsEx**

`C:\Users...\pawno\include\fixes.inc(10836) : warning 219: local variable "engine" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(10837) : warning 219: local variable "lights" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(10838) : warning 219: local variable "alarm" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(10839) : warning 219: local variable "doors" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(10840) : warning 219: local variable "bonnet" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(10841) : warning 219: local variable "boot" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(10842) : warning 219: local variable "objective" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(11020) : warning 219: local variable "engine" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(11021) : warning 219: local variable "lights" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(11022) : warning 219: local variable "alarm" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(11023) : warning 219: local variable "doors" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(11024) : warning 219: local variable "bonnet" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(11025) : warning 219: local variable "boot" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(11026) : warning 219: local variable "objective" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14333) : warning 219: local variable "engine" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14333) : warning 219: local variable "lights" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14333) : warning 219: local variable "alarm" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14333) : warning 219: local variable "doors" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14333) : warning 219: local variable "bonnet" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14333) : warning 219: local variable "boot" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14333) : warning 219: local variable "objective" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14362) : warning 219: local variable "engine" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14362) : warning 219: local variable "lights" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14362) : warning 219: local variable "alarm" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14362) : warning 219: local variable "doors" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14362) : warning 219: local variable "bonnet" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14362) : warning 219: local variable "boot" shadows a variable at a preceding level
C:\Users...\pawno\include\fixes.inc(14362) : warning 219: local variable "objective" shadows a variable at a preceding level`

**Comment by mbicanic96** [comment]
Fixed by renaming variables in gamemode - added 'v_' in front of them (v_engine)

**Comment by Y-Less** [comment]
That is an indication that you have poorly named globals, which is not something we can really avoid.

fixes.inc uses very strict, common, naming conventions to avoid these situations - simple names are reserved for locals, globals are prefixed, macros are in `SCREAMING_CASE` and functions are in `CamelCase`.  If other people don't follow these community-wide, and years old conventions, there's literally nothing we can do about it.
