### ISSUE TITLE
OnPlayerUpdate stops being called

### ISSUE THREAD

**Issue by punkochel** [Open-GTO/sa-mp-fixes#164]
At calling ShowPlayerDialog, stops working OnPlayerUpdate, but when closed window dialog everything works as it should. Tested with one include fixes in the new.pwn, with out any settings.

**Comment by Y-Less** [comment]
This is the `BypassDialog` fix.  It is intended to stop people cheating by moving around with a dialog open, but you can disable it if you want that behaviour.
