### ISSUE TITLE
i get too many warnings

### ISSUE THREAD

**Issue by DomnulEMi** [Open-GTO/sa-mp-fixes#172]
what am i doing wrog? why do i get so many warnings?

D:\GameMode PG\pawno\include\fixes.inc(19434) : warning 219: local variable "animation" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20251) : warning 219: local variable "engine" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20252) : warning 219: local variable "lights" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20253) : warning 219: local variable "alarm" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20254) : warning 219: local variable "doors" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20255) : warning 219: local variable "bonnet" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20256) : warning 219: local variable "boot" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20257) : warning 219: local variable "objective" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20470) : warning 219: local variable "engine" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20471) : warning 219: local variable "lights" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20472) : warning 219: local variable "alarm" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20473) : warning 219: local variable "doors" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20474) : warning 219: local variable "bonnet" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20475) : warning 219: local variable "boot" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(20476) : warning 219: local variable "objective" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24955) : warning 219: local variable "engine" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24955) : warning 219: local variable "lights" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24955) : warning 219: local variable "alarm" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24955) : warning 219: local variable "doors" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24955) : warning 219: local variable "bonnet" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24955) : warning 219: local variable "boot" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24955) : warning 219: local variable "objective" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24988) : warning 219: local variable "engine" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24988) : warning 219: local variable "lights" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24988) : warning 219: local variable "alarm" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24988) : warning 219: local variable "doors" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24988) : warning 219: local variable "bonnet" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24988) : warning 219: local variable "boot" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(24988) : warning 219: local variable "objective" shadows a variable at a preceding level
D:\GameMode PG\pawno\include\fixes.inc(26454) : warning 234: function is deprecated (symbol "FIXES_GetServerVarAsInt") Use `GetConsoleVarAsInt`

D:\GameMode PG\pawno\include\YSI\internal\y_funcinc.inc(75) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\k_functions.inc(154) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\k_functions.inc(161) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(46) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(46) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(46) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(46) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(90) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(90) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(90) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(90) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(98) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(98) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(98) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\fly.inc(98) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\strlib.inc(475) : warning 201: redefinition of constant/macro (symbol "ispacked(%1)")
D:\GameMode PG\pawno\include\progress.inc(83) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(84) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(87) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(87) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(129) : warning 229: index tag mismatch (symbol "pbar_Index@YSII_Ag")
D:\GameMode PG\pawno\include\progress.inc(166) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(167) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(168) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(169) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(170) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(171) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(172) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(173) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(174) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(175) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(176) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(177) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(180) : warning 229: index tag mismatch (symbol "pbar_Index@YSII_Ag")
D:\GameMode PG\pawno\include\progress.inc(195) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(196) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(197) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(200) : warning 229: index tag mismatch (symbol "pbar_Index@YSII_Ag")
D:\GameMode PG\pawno\include\progress.inc(213) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(215) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(216) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(217) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(227) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(229) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(230) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(231) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(252) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(253) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(254) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(256) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(260) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(260) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(260) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(261) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(261) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(262) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(262) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(262) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(263) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(263) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(339) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(343) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(378) : warning 229: index tag mismatch (symbol "pbar_Index@YSII_Ag")
D:\GameMode PG\pawno\include\progress.inc(404) : warning 229: index tag mismatch (symbol "pbar_Index@YSII_Ag")
D:\GameMode PG\pawno\include\progress.inc(485) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(485) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(502) : warning 229: index tag mismatch (symbol "pbar_Index@YSII_Ag")
D:\GameMode PG\pawno\include\progress.inc(629) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(629) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(631) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(633) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(635) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(640) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(640 -- 642) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(640 -- 643) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(640 -- 644) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(640 -- 646) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(651) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(651 -- 653) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(651 -- 654) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(651 -- 655) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(651 -- 657) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(661) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\progress.inc(672) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\pg-ac.inc(44) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\pg-ac.inc(130) : warning 201: redefinition of constant/macro (symbol "TogglePlayerSpectating")
D:\GameMode PG\pawno\include\pg-ac.inc(148) : warning 201: redefinition of constant/macro (symbol "SetPlayerCheckpoint")
D:\GameMode PG\pawno\include\pg-ac.inc(154) : warning 201: redefinition of constant/macro (symbol "DisablePlayerCheckpoint")
D:\GameMode PG\pawno\include\pg-ac.inc(160) : warning 201: redefinition of constant/macro (symbol "SetPlayerPosFindZ")
D:\GameMode PG\pawno\include\pg-ac.inc(166) : warning 201: redefinition of constant/macro (symbol "SetPlayerPos")
D:\GameMode PG\pawno\include\pg-ac.inc(178) : warning 201: redefinition of constant/macro (symbol "SetVehiclePos")
D:\GameMode PG\pawno\include\pg-ac.inc(217) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\pg-ac.inc(231) : warning 213: tag mismatch
D:\GameMode PG\pawno\include\pg-ac.inc(274) : warning 213: tag mismatch
D:\GameMode PG\gamemodes\PG.pwn(29) : error 021: symbol already defined: "gpci"
D:\GameMode PG\gamemodes\PG.pwn(58) : warning 201: redefinition of constant/macro (symbol "SetWorldTime")
D:\GameMode PG\gamemodes\PG.pwn(1438) : warning 213: tag mismatch
D:\GameMode PG\gamemodes\PG.pwn(1439) : warning 213: tag mismatch
D:\GameMode PG\gamemodes\PG.pwn(1440) : warning 213: tag mismatch
D:\GameMode PG\gamemodes\PG.pwn(3483) : warning 201: redefinition of constant/macro (symbol "DestroyVehicle")
D:\GameMode PG\gamemodes\PG.pwn(3526) : error 017: undefined symbol "do_not_use_tabsize_0"
D:\GameMode PG\gamemodes\PG.pwn(6605) : warning 213: tag mismatch
D:\GameMode PG\gamemodes\PG.pwn(62607) : warning 234: function is deprecated (symbol "gpci") Use `GPCI`.

**Comment by Y-Less** [comment]
The first half are because you have global variables with generic names like `boot`.  The second half are mostly covered in the readme, or pg-ac incorrectly using ALS hooking.
