### ISSUE TITLE
Error 010

### ISSUE THREAD

**Issue by ToshimiYuki09** [Open-GTO/sa-mp-fixes#174]
I Don't Know How To Fix This Error Can Someone Help Me Fix It ?![Screenshot_20230412-140105_Microsoft Remote Desktop.jpg](https://user-images.githubusercontent.com/111070061/231394587-d27da2bf-69a7-403e-b1bd-dfb532cda112.jpg)

**Comment by DEntis-T** [comment]
remove those useless defines
