### ISSUE TITLE
Default disabled fixes

### ISSUE THREAD

**Issue by Y-Less** [Open-GTO/sa-mp-fixes#22]
The following fixes are all disabled by default, and I suspect most people don't even know they exist or would know how to enable them:

`GetSVarString`
`GetPVarString`
`GetPlayerWeaponData`
`GetPlayerDialog` (Speaking of which, [this line](https://github.com/rt-2/sa-mp-fixes/blob/9a7b111a84c4925157ede4db4eb800f824ef596d/fixes.inc#L7629) is wrong, since the point is that that native doesn't exist, so the `BAD_` version shouldn't be defined).
`file_inc`
`random`
`HideMenuForPlayer_2` (Speaking of which, I don't think this does what it claims to).
`HideGameText` (Maybe combine with `GetPlayerDialog` in a `FIX_MissingNatives` define or put under the existing `FIX_Natives`).
`GetPlayerPoolSize`

Should they be reviewed?

`GetSVarString` and `GetPVarString` I can't see a reason to have disabled.
`GetPlayerWeaponData` same.
`GetPlayerDialog` and `HideGameText` are useful and probably should exist even though they don't and adding functions isn't the main point.  We should remain wary of adding new functions, but I think those two are justifiable as default enabled now.
`file_inc` adds a lot of overhead, and most scripts should never need it if they correctly check that files were opened.
`random` was disabled because I was never convinced that it was a bug, more a feature expansion similar to `HideGameText`.
`GetPlayerPoolSize` as I understand it the concern was that it could break scripts; however, every use I've seen of this function was `for (new i = 0; i <= GetPlayerPoolSize(); ++i)` or the better `for (new i = 0, j = GetPlayerPoolSize(); i <= j; ++i)`, which would work better with the fix (as should be the case with fixes).

**Comment by ziggi** [comment]
> `GetSVarString` and `GetPVarString` I can't see a reason to have disabled.

This fix needs only for people who use non English languages in the scripts.

> `GetPlayerWeaponData` same.

This fix can broke some scripts, but I agree that this should be enabled by default.

> `GetPlayerDialog` and `HideGameText` are useful and probably should exist even though they don't and adding functions isn't the main point. We should remain wary of adding new functions, but I think those two are justifiable as default enabled now.

Agreed.

> `file_inc` adds a lot of overhead, and most scripts should never need it if they correctly check that files were opened.

Yes it is.

> `random` was disabled because I was never convinced that it was a bug, more a feature expansion similar to `HideGameText`.

Agreed.

> `GetPlayerPoolSize` as I understand it the concern was that it could break scripts; however, every use I've seen of this function was `for (new i = 0; i <= GetPlayerPoolSize(); ++i)` or the better `for (new i = 0, j = GetPlayerPoolSize(); i <= j; ++i)`, which would work better with the fix (as should be the case with fixes).

Agreed.
