### ISSUE TITLE
FIXES_Single cleanup

### ISSUE THREAD

**Issue by Y-Less** [Open-GTO/sa-mp-fixes#25]
There are probably literally hundreds of pieces of code like this:

```pawn
#if FIXES_Single
	FIXES_gsLastCash[playerid] = 0;
#else
	SetPVarInt(playerid, FIXES_pvarPlayerLastCash, 0);
#endif
```

This is very poor design and incredibly fragile - easy to make a mistake, use the wrong one, update one but not the other, etc.  I don't know WHY I did it this way originally, it should be:

```pawn
#if FIXES_Single
	#define FIXES_SET(%0,%1,%2) (FIXES_gs%0[%1] = %2)
#else
	#define FIXES_SET(%0,%1,%2) SetPVarInt(%1, FIXES_pvar%0, %2)
#endif
```

```pawn
FIXES_SET(LastCash, playerid, 0);
```

Or something very similar, obviously with corresponding `GET` equivalents.

**Comment by ziggi** [comment]
But we have different methods of storing variables in single mode:
FIXES_gsPlayerBools: https://github.com/Open-GTO/sa-mp-fixes/blob/master/fixes.inc#L6676-L6680

**Comment by Y-Less** [comment]
I'm not saying do it for every one.

**Comment by ziggi** [comment]
Done.
