### ISSUE TITLE
Can't enter Busses as passengers

### ISSUE THREAD

**Issue by rt-2** [Open-GTO/sa-mp-fixes#27]
Here is the gamemode I made to test:
```
//
// SA-MP Fixes Test Script #1(Can't enter Busses as passengers)
//      by: rt-2
//      date: 2017-05-19
//
//This script prevent entry if you
//      enter one of the busses as passenger.

// Main Libraries
#include <a_samp>
#include <crashdetect>
// Pawn fixes
#define FIXES_Single 1
#include <fixes>

public OnGameModeInit()
{

	SetGameModeText("Test Script");
	AddPlayerClass(random(100), 1958.3783, 1343.1572, 15.3746, 269.1425, 0, 0, 0, 0, 0, 0);

	AddStaticVehicle(431, 2040.0, 1363.0, 17.0, 180.0, 0, 1);//bus
	AddStaticVehicle(437, 2040.0, 1383.0, 17.0, 180.0, 0, 1);//coach

	return 1;
}
main()
{
	print("\n----------------------------------");
	printf(" 'SA-MP Fixes Test Script' by rt-2 ");
	print("----------------------------------\n");
}
```
I have tried investigating myself but without success.
I'd like to know where it comes from at least while I wait for a fix I could deactivate temporally the concerned fix(es).
Thank you,
rt-2

**Comment by ziggi** [comment]
It's a FIX_OnPlayerEnterVehicle fix

**Comment by rt-2** [comment]
Thank you for your answer.
Unfortunatly, adding:
```
#define FIX_OnPlayerEnterVehicle 0
#define FIX_OnPlayerEnterVehicle_2 0
```
before ``#include <fixes>`` doesn't fix it for me.
Thank you,
rt-2

**Comment by ziggi** [comment]
FIX_PassengerSeating

**Comment by rt-2** [comment]
I also tried it without success.
Have you been able to reproduce the bug with my small gamemode?
Thank you,
rt-2

**Comment by ziggi** [comment]
Yea, I'm absolutely sure in this. Should be fixed now.

**Comment by rt-2** [comment]
I havent tried on this gamemode only my huge with filterscripts, my mistake.
And this does fix it.
Thank you very much,
rt-2
P.S. It seems if I have a gamemode and filterscript, this check will be done multiple times, isn't unecessary?

**Comment by Y-Less** [comment]
It will if you compile with FIXES_Single - that is only to be used if you don't have filterscripts, which you do.

**Comment by rt-2** [comment]
That's the thing, I compiled everything with ``FIXES_Single 0``, and when I made the changes, I recompiled only the gamemode and tried, but it seemed like a filterscript was still blocking the entry, that's where I got puzzled, with ``FIXES_Single 0`` the work/check was still done in a filterscript it seemed.
Thank you,
rt-2
EDIT: What I said can't be true, disregard.
