### ISSUE TITLE
SetPlayerSkin breaks sitting in cars

### ISSUE THREAD

**Issue by rt-2** [Open-GTO/sa-mp-fixes#28]
Hi,
when a player is sitting in a vehicle, if using ``SetPlayerSkin``, the animation will stay correct for the same player, but for any other player streaming, the player will loose the animation.
It is not doing that on the bike I tested.
Thank you,
rt-2

**Comment by Y-Less** [comment]
Does reapplying `PutPlayerInVehicle` fix it?  If so, just need to wrap `SetPlayerSkin` and reput them in a vehicle, something like:

```pawn
stock FIXES_SetPlayerSkin(playerid, skinid)
{
	new
		ret = SetPlayerSkin(playerid, skinid),
		vehicleid = GetPlayerVehicle(playerid);
	if (vehicleid)
		PutPlayerInVehicle(playerid, vehicleid, /* forgot how to get seat ID */);
	return ret;
}
```

**Comment by rt-2** [comment]
Isn't this already what FiX_SetPlayerSkin is doing already?
Thank you,
rt-2

**Comment by Y-Less** [comment]
Sorry, I thought you were reporting another SA:MP bug to fix, not a problem with an existing fix.

**Comment by rt-2** [comment]
Well the original fix only talks about bikes in its description also.
I was not sure.
rt-2

**Comment by ziggi** [comment]
Try this please: https://github.com/Open-GTO/sa-mp-fixes/commit/56e55a7b642581be8f6c21517f7fb0a7e9a97265

**Comment by Y-Less** [comment]
That's a much better solution than mine if it works - I was thinking about various things like putting them back in the vehicle in OnPlayerStreamIn the first time they appear for any given player - a lot of extra data and code!

**Comment by rt-2** [comment]
I tried to test this morning but was unable to reproduce the bug for some reason, I'll test in my main gamemode and get back to you later...

**Comment by rt-2** [comment]
Hi again,
Sorry for the delay, I have a lot to test/debug, and so small time.
I am not able to reproduce in a small script or find what is causing this in my gamemode, but your commit fixed it.
I tested with and without and I saw the bug then it was fixed with the modification.
Thank you,
rt-2
