### ISSUE TITLE
const-correctness

### ISSUE THREAD

**Issue by Y-Less** [Open-GTO/sa-mp-fixes#29]
Several native functions take regular strings when they could take constant strings.  This is an issue when you want your own function to take a constant string to ensure that it is never modified, and has actually come up once in fixes.inc itself:

[External const version](https://github.com/Open-GTO/sa-mp-fixes/blob/56e55a7b642581be8f6c21517f7fb0a7e9a97265/fixes.inc#L1998)

[Internal static version](https://github.com/Open-GTO/sa-mp-fixes/blob/56e55a7b642581be8f6c21517f7fb0a7e9a97265/fixes.inc#L2011)

There are two copies of that because they are used by different functions that take different string types (`TextDrawCreate` for the static version within the include, and `GameTextForPlayer` for the const version).  I did think there was an instance where a variable was used in a macro so visible to end-user code (and thus, in theory, modifiable to break fixes.inc's uses, but I can't see it).

Anyway, const-correctness is important for good code and compiler checking:

https://duckduckgo.com/html/?q=const%20correctness

As another example:

```pawn
native SetTimerEx(funcname[], interval, repeating, const format[], {Float,_}:...);
native CallRemoteFunction(const function[], const format[], {Float,_}:...);
```

Why is the function name in `CallRemoteFunction` `const`, but not in `SetTimerEx`?  Neither will modify the variable, so it should be so that user code can use more constants in the correct places as well.  Adding `const` to natives that did not previously have them will introduce no backwards-compatability problems since any old non-const code can still be given:

```pawn
native CONST_SetTimerEx(const funcname[], interval, repeating, const format[], {Float,_}:...) = SetTimerEx;
#define SetTimerEx CONST_SetTimerEx
// Obviously with ALS...
```

 Or even:

```pawn
native CONST_SetTimerEx(const funcname[], interval, repeating, const format[], FIXES_TAG_TYPES:...) = SetTimerEx;
#define SetTimerEx CONST_SetTimerEx
// Obviously with ALS...
```

Then adding the ability at a later date to even expand the number of types a function can take (why shouldn't you be able to pass file handles (`File:`) this way for example)?

**Comment by Y-Less** [comment]
For numbers this doesn't matter - they are always passed by value, so changes are not reflected back anyway.  Arrays are the same as strings for this.  Reference parameters CAN be `const`, but that makes no sense (and should probably be a compiler warning IMHO - `const` means "don't change this", `&` means "this will be changed and I'll give you the result").  I just found out that varargs can also be `const`, i.e. `const ...`, but the const status here is totally ignored (probably because you can't enforce it within `setarg()`).

**Comment by ziggi** [comment]
This changes can broke much code. Because many people uses ALS for this functions, and sometimes they change values for string variables (as for GetSVarString fix). I know what use `const` "everywhere" it's a good way, but not in SA-MP with limited Pawn.

**Comment by Y-Less** [comment]
No it won't - you can still call const parameters with non-const data, just not the other way around.

**Comment by Y-Less** [comment]
If you look at the GetSVarString fix, that isn't even affected.  The return value isn't const.  All existing code that calls natives must have been non-const before, because const would have been an error, and non-const code will still work.
