### ISSUE TITLE
GetPlayerWorldBounds + default values change

### ISSUE THREAD

**Issue by IstuntmanI** [Open-GTO/sa-mp-fixes#34]
I see that this include also stores the min/max X, Y coordinates for ```SetPlayerWorldBounds```, so a ```GetPlayerWorldBounds``` function could be created, just like ```GetPlayerDialog```.
Those variables are initialized to 0.0 in this include, but as [the wiki](http://wiki.sa-mp.com/wiki/SetPlayerWorldBounds) says, the default values are 20000.0, -20000.0, 20000.0, -20000.0, so these values should be used instead. Also, boundaries should be set to those values instead of negative/positive infinity if the area is too small (under ```SetPlayerWorldBounds```).

**Comment by Y-Less** [comment]
Can anyone confirm those?  They seem plausible but I'm never sure about information on the wiki.  This can also add a `ClearPlayerWorldBounds` function (or macro).

**Comment by IstuntmanI** [comment]
I just tested them again and the world boundaries are exactly there. That function would be fine too.

**Comment by Y-Less** [comment]
OK then, I'll get on it.

**Comment by Y-Less** [comment]
I've written the code, but it needs testing in-game.

**Comment by ziggi** [comment]
I did some tests, and everything seems fine.

**Comment by Y-Less** [comment]
Cool.  I've actually now installed SA/SA:MP, so can do more useful testing!  I actually realised earlier today, not only did I not have SA installed, actually a lot of the time I don't even get my code as far as a full .amx - I often jus compile to .lst or .asm and call it enough (that usually is enough for what I do).
