### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by Y-Less** [Open-GTO/sa-mp-fixes#37]
They are inaccurate and don't handle strings or arrays well (they just pass the memory location, which might become invalid or get overwritten).  There is a library for fixing them (in fact there are several and at least two plugins), but I don't know if the problem should also be addressed in this library for completion's sake - keep everything in one place.

**Comment by IstuntmanI** [comment]
This would be a pretty big fix, that is better as a plugin. But yeah, "keep everything in one place" is why it should also be in this include. I guess that it should be disabled by default, I think that Pawn will make it slow and with a stupid timer limit.

**Comment by Y-Less** [comment]
That is the main problem - it will be very hard to implement well and sufficiently flexibly.

**Comment by Y-Less** [comment]
Note that I'm just trying to list almost everything that could be fixed, so there's a reference somewhere.  Some may never by included in this include.

**Comment by rt-2** [comment]
I think y_timer does a good job about it, also some includes take into account that lag, so that could actually be destructive. I'm talking about fix includes or anticheats.
That's my opinion, but I feel like most people will think it's not a good argument.

**Comment by WoutProvost** [comment]
I'm definitely in favour of keeping everything in one place. On the other hand, I'm using [Timerfix](http://forum.sa-mp.com/showthread.php?t=435525) and am pretty satisfied with that.
