### ISSUE TITLE
Incompatibility with Y_Includes

### ISSUE THREAD

**Issue by rt-2** [Open-GTO/sa-mp-fixes#41]
Hi, it took me some time to understand, because the compiler ONLY crashes when there is no errors but, when I compile this with Zeex's compiler, it crashes.
```
#include <a_samp>
#include <fixes>
#include <YSI\y_master>
```
There is no error the compiler simply crashes on my end.
Thank you,
rt-2

**Comment by Y-Less** [comment]
I just tested with the latest versions of all those things - YSI, fixes.inc, compiler, and this code:

```pawn
#include <a_samp>
#include <sa-mp-fixes\fixes>
#include <YSI\y_master>

main()
{
	print("\n----------------------------------");
	print(" Blank Gamemode by your name here");
	print("----------------------------------\n");
}
```

Compiled fine with no crash.  If with all the latest versions it still does it, I will need more information like your exact code.

**Comment by ziggi** [comment]
And it would be great if you test this on older versions of fixes and YSI.

**Comment by Y-Less** [comment]
While it is good to test on older versions, any fix would require a new version anyway, so the answer becomes "use the latest version", while apparently the new version doesn't do this, so the answer is "use the latest version".

**Comment by Y-Less** [comment]
Or exactly which versions are you using?  At least that way I can reproduce the issue and get to understand the cause.

**Comment by rt-2** [comment]
Aaaand I wake up this morning and my tests are down the drain, my main script still crashes on compile, but those 3 lines doesn't anymore this morning. I swear I hate this language it's not even stable smh.
I have currently have a 6000 lines code that, if I remove ANYTHING from it, it compiles without crashes, but when I try compiling as is, it crashes. It started when I tried to add a izcmd command, it crashed, when I removed it it didn't anymore, but when I left the new one in and removed another one it worked too. And I tried removing about 50 other lines that were for another purpose, and and still compile great, but the entire script doesn't. I have no idea where to look, I've tried to fix that for litteraly hours. Yesterday those 3 lines crashed my compiler, today not. I have sufficient ram.
So right now I cannot know what is causing this because anything I remove makes the script works, so I can't devide it into 2 to try to find which half etc... The only think that doesn't change the result is if I stop including stuff like anticheat or other include I can remove without errors, this problem also cannot happen if there is any errors. The only include I can remove to fix this is ``fixes.inc``, others have no effects.
Anyone wanna help prevent my suicide? (joke)
thank you,
rt-2

**Comment by rt-2** [comment]
Updated YSI, still same problem (after 2h of debugging).

**Comment by rt-2** [comment]
I really had some difficulties. I'm not sure, but I think updating YSI and doing other stuff fixed the issue.
Thank you for your idea,
rt-2

**Comment by Y-Less** [comment]
That is very odd, I'm happy to take a look if it happens again.  That's usually a sign of several things conflicting with each other, and tracking that down can be tricky but I've gotten fairly good at it.  It could well be something in fixes.inc or YSI - they both do strange things, or a combination of them and more.

The likely reason only removing fixes.inc had no other effects is that it is designed to be drop-in, so removing it shouldn't stop code compiling.

**Comment by rt-2** [comment]
Yes, that and other includes that doesn't add any new function like the anticheat, those were the only one I could remove without causing errors because of missing functions.
