### ISSUE TITLE
TextDrawCreate/SetString, GameTextForPlayer/All last character as space

### ISSUE THREAD

**Issue by IstuntmanI** [Open-GTO/sa-mp-fixes#55]
- Problem:

From the [TextDrawCreate](http://wiki.sa-mp.com/wiki/TextDrawCreate) wiki page:
> If the last character in the text is a space (" "), the text will all be blank. 

It also happens for gametexts. Not sure if it happens in TextDrawSetString too (probably does).

- Possible solution/implementation:

Hook TextDrawCreate/TextDrawSetString/GameTextForPlayer/GameTextForAll and let them look like
```pawn
stock ALS_HookedFunction( [..,] text[ ] [, ..] )
{
	if( text[ 0 ] != EOS && text[ 1 ] != EOS )
	{
		new lLastPos = 0;

		for( new i = 1; text[ i ] != EOS; i ++ )
		{
			if( text[ i ] != ' ' )
				lLastPos = i;
		}

		text[ lLastPos + 1 ] = EOS;
	}

	return HookedFunction( [..,] text [, ..] );
}
```
I think that I also managed to allow " " as a valid text. Maybe someone can come with a better/shorter alternative, if possible. I didn't use ```strlen``` because the code would be slower. Here are the tests:
```
'' -> ''
' ' -> ' '
'a' -> 'a'
'a ' -> 'a'
'ab' -> 'ab'
'ab ' -> 'ab'
'a   b' -> 'a   b'
'a   b ' -> 'a   b'
'a   b   ' -> 'a   b'
```

**Comment by Y-Less** [comment]
I'm not concinced strlen would be slower - use it to find the end and work backwards.  You are already going through the whole string, why not do it in C instead?
