### ISSUE TITLE
GetConsoleVarAsString used on float results in server crash

### ISSUE THREAD

**Issue by WoutProvost** [Open-GTO/sa-mp-fixes#73]
Everything explained in [this thread](http://forum.sa-mp.com/showthread.php?t=613615)

**Comment by Y-Less** [comment]
Unfortunately, as also detailed in that thread, this isn't easy to fix in pure PAWN.  There are four options I can see:

1) Ignore it.
2) Wait (indefinately) for the fixes-plugin.
3) Use the plugin-based fix in that thread (requires a plugin, so won't be done in this include).
4) Use [DANGEROUS_SERVER_ROOT](https://github.com/Misiur/YSI/blob/master/links.rar) (no plugin required).
(5) A hybrid of 3) and 4) that detects the best method.

**Comment by Y-Less** [comment]
Merged in #76
