### ISSUE TITLE
Different OnFilterScriptExit and OnPlayerDisconnect behaviour when including fixes.inc

### ISSUE THREAD

**Issue by WoutProvost** [Open-GTO/sa-mp-fixes#77]
**Scenario 1:**
- Gamemode with 6 NPCs. Uses fixes.inc.
- Filterscript with 1 NPC.
- Console log when using `unloadfs`:
```
unloadfs mytestfs
FS EXIT
PLAYER DC
[npc:part] mytestnpc has left the server (49:0)
  Filterscript 'mytestfs.amx' unloaded.
```

**Scenario 2:**
- Gamemode with 6 NPCs. Uses fixes.inc.
- Filterscript with 1 NPC. **Uses fixes.inc.**
- Console log when using `unloadfs`:
```
unloadfs mytestfs
PLAYER DC
PLAYER DC
PLAYER DC
PLAYER DC
PLAYER DC
PLAYER DC
PLAYER DC
FS EXIT
[npc:part] mytestnpc has left the server (49:0)
  Filterscript 'mytestfs.amx' unloaded.
```
Include order is:
```
#include <a_samp>
#include <fixes>
#include <others>
```
First scenario when I was writing the filterscript. Second scenario when I included fixes.inc in the filterscript.
- Why is the order of OnFilterScriptExit and OnPlayerDisconnect different when using fixes.inc?
- Why is OnPlayerDisconnect called for the 6 NPCs in the gamemode when using fixes.inc?

**Comment by Y-Less** [comment]
1) The order is different because changing things is what fixes.inc does.  If you close the filterscript, `OnFilterScriptExit` will be called - this should be the LAST thing that happens, so things like database connections can be closed and other resources released.  If it was not the last thing called, how would you know when all players were done with?  If you had to, say, leave the database connection open to save the disconnecting players, how would you know when to close it?

2) When a filterscript ends, it might have information about all players to save, so `OnPlayerDisconnect` is called for all players.  NPCs are just a type of player.  It doesn't matter where they were created, the FS still needs to be informed that it will no longer have access to them.  Think of it less like `OnPlayerLeaveServer` and more like `OnScriptLoseAccessToPlayer`.

**Comment by WoutProvost** [comment]
1. Is this change not worth documenting then?
2. Ah, I see ... It's even documented on the readme. However, the explanation given here is much better.

**Comment by WoutProvost** [comment]
Actually, after reading your explanations again, I don't see why the changes are necessary.

> If you close the filterscript, OnFilterScriptExit will be called - this should be the LAST thing that happens, so things like database connections can be closed and other resources released.

When this callback is called you should clean up everything anyway, that's the responsibility of the scripter. Say your script has an array of player information, you should loop through that array anyway to save last changes and clean up everything.
```Pawn
new myArray[MAX_PLAYERS] = {-1, ...};
new DB:myDBHandle;

public OnFilterScriptExit()
{
	for(new playerid = 0; playerid < MAX_PLAYERS; playerid++) {
		//Push last changes to DB, because the script is exiting
		format(query, sizeof(query), "... %d ...", myArray[playerid]);
		db_query(myDBHandle, "query");

		//Cleanup variables
		myArray[playerid] = -1;
	}

	//Close DB after everything else is done
	db_close(myDBHandle);
	return 1;
}
```

> If it was not the last thing called, how would you know when all players were done with?

Since the script is already exiting, any other callbacks being called should'nt matter anymore, because as soon as OnFilterScriptExit is called, you should regard your script as in the process of being shut down. 

In this case it is players being handled differently. But then why not loop over all other things, like vehicles, pickups, ... Shouldn't the script also be informed that it will not have access to those entities as well?

> If you had to, say, leave the database connection open to save the disconnecting players, how would you know when to close it?

After doing everything else in OnFilterScriptExit, you close the DB, because you know that you've pushed the last changes.

> When a filterscript ends, it might have information about all players to save, so OnPlayerDisconnect is called for all players. NPCs are just a type of player.

It might also have information in an array of user-defined types (in Pawn more like enums ...), but you don't have any other choice than to clean them up in OnFilterScriptExit.

> It doesn't matter where they were created, the FS still needs to be informed that it will no longer have access to them.

OK, change player for say server variable. It doesn't matter where they were created, but the FS still needs to be informed that it will no longer have access to them. Say there was an `OnServerVariableDelete(varname[])`, would you also call this callback for every server variable on filterscript exit, because the filterscript doesn't have access to it anymore?

> Think of it less like OnPlayerLeaveServer and more like OnScriptLoseAccessToPlayer.

A name should indicate what it does. Implementing these changes, breaks that. It is not intuitive any more. The fact that you had to explain what the callback should be interpreted as, shows that.

**Comment by Y-Less** [comment]
Most of that would require adding far more logic in to OnPlayerDisconnect.  Instead of just:

```pawn
public OnPlayerDisconnect(whatever)
{
    SavePlayer(playerid);
}
```

You now have:

```pawn
public OnPlayerDisconnect(whatever)
{
    if (!ShutDown())
        SavePlayer(playerid);
}
```

Maybe that's not a lot, but the code has already doubled because we need to handle the case of that callback being called after OnFilterScriptExit (which makes no sense - why would anything be called after the script has ended)?

**Comment by WoutProvost** [comment]
> Why would anything be called after the script has ended?

Yes, I agree, but changing the meaning of the callback because that's the case, shouldn't be the solution. The player doesn't disconnect from the script, he disconnects from the server.

I can think of some cases where the current implementation would affect things.
```Pawn
//GLOBAL:
//Some player with special meaning, kept track of by wathever solution: DB, file, server var, ... doesn't matter.
//I use server vars here. For the special meaning, I use the stupid example of giving him money based on a timer.
//SVar: specialPlayer

//FILTERSCRIPT:
public OnPlayerDisconnect(...)
{
	//FS thinks the player is actually leaving the server, so changes the global variable.
	//Even though he is not leaving the server, but the FS is just exiting.
	new specialPlayer = GetSVarInt("specialPlayer");
	if(specialPlayer == playerid) {
		SetSVarInt("specialPlayer", INVALID_PLAYER_ID);
	}
}

//GAMEMODE:
forward Privilege();
public Privilege() {
	//This won't work anymore
	new specialPlayer = GetSVarInt("specialPlayer");
	GivePlayerMoney(specialPlayer, 1000);
}
```

(Before anyone mentions it, I know I can turn that particular 'fix' off, but that's not what's being discussed here.)
