### ISSUE TITLE
New 0.3.8 server.cfg options

### ISSUE THREAD

**Issue by Y-Less** [Open-GTO/sa-mp-fixes#84]
I know `useartwork`, `sleep`, `mtu`.  Any more that need adding to `GetServerVarAsInt` (or other)?

**Comment by ziggi** [comment]
I think `sleep` was in 0.3.7 too

**Comment by WoutProvost** [comment]
Just use the varlist console command.

**Comment by WoutProvost** [comment]
See also http://wiki.sa-mp.com/wiki/Server.cfg. Just CTRL-F on that page for 0.3.8.
