### ISSUE TITLE
Error #017

### ISSUE THREAD

**Issue by XEGARE** [Open-GTO/sa-mp-fixes#85]
Hi.
`c:\server\pawno\include\fixes.inc(1805) : error 017: undefined symbol "__PawnBuild"`

Error code:
`#if defined __PawnBuild && __PawnBuild >= 4`

**Comment by SysadminJeroen** [comment]
Try to compile it with the community compiler (previously called Zeex's
Pawn Compiler)

Download: https://github.com/Southclaws/pawn/releases

More info: https://github.com/Southclaws/pawn/wiki/What's-new#__pawnbuild

Op 22 jan. 2018 15:02 schreef "XEGARE" <notifications@github.com>:

**Comment by Y-Less** [comment]
That would happen when already using that compiler, but a slightly older version.  I've fixed it.
