### ISSUE TITLE
Stuntplane tailwheel

### ISSUE THREAD

**Issue by WoutProvost** [Open-GTO/sa-mp-fixes#9]
This bug: **With the stuntplane, if you respawn it or repair it with RepairVehicle, the tailwheel only appears then** found in  [this](http://forum.sa-mp.com/showthread.php?t=151670) thread, can also be fixed with UpdateVehicleDamageStatus.

Creating a hook for CreateVehicle, AddStaticVehicle, AddStaticVehicleEx and executing one of the 2 functions in it should work I think?

**Comment by ziggi** [comment]
Yep, I think this should work.

**Comment by WoutProvost** [comment]
I forked the repository, see the commits [here](https://github.com/WoutProvost/sa-mp-fixes/commits/master).
Unfortunately it isn't as simple as I thought it would be (that's probably also the reason why I haven't found another attempt like this, to fix the bug).
Calling **UpdateVehicleDamageStatus** right after any of the 3 create functions doesn't seem to reslove the problem. It could have to do with that it takes some time for the server to actually spawn the vehicle (no proof, just speculating here), like so:
- call the create the vehicle function
- my hook immediately updates the damage status
- server actually spawns the vehicle
- previously set damage status is overriden by the spawning of the vehicle

When I however call **UpdateVehicleDamageStatus** manually afterwards, the tailwheel does appear.
The only fix I can think of is to create a timer I think.

**Comment by WoutProvost** [comment]
So, I have done some tests.
- First I added a timer of 100 ms. Started the server, joined it and ... the timer didn't seem to affect anything.
- Then I raise the interval to 1000 ms. Started the server, joined it and ... the timer didn't seem to affect anything.
- Then I created a separate filterscript, which can be found [here](https://gist.github.com/WoutProvost/cf82bc4fb3dfb98c23e5265c4c7dc8c1) and left the interval at 1000 ms. Started the server, joined it, loaded the filterscript and executed the command. Finally the tailwheel appeared! But there still was no tailwheel for the stuntplanes spawned in OnGameModeInit.
- I spawned some more Stuntplanes with the command and sometimes the tailwheel appeared, sometimes it did not.
- So that's when I added the benchmark with GetTickCount to check (see the above link) how long it actually takes the server to create and stream in the vehicle. The results are ... quite random. From a few milliseconds to over a second and a half:
  ![Benchmark results](https://www.dropbox.com/s/ecfbzz5pw6xzhb1/Naamloos.png?raw=1)
- So I think a timer interval of about 2000 ms should be good I guess, although that is 2 seconds!
- After that test I did some more testing to find out why the Stunplanes spawned with the command did get a tailwheel most of the time and why the Stunplanes spawned in OnGameModeInit never did. And I found out that it is actually a streaming issue. When I got far enough away from the Stuntplane that I spawned with the command (the one that had the tailwheel) so that it streamed out for me, and I returned to it, the tailwheel was gone again.
- I also found out that when the Stuntplane has a tailwheel, the enter animation bugs. When it doesn't have a tailwheel (anymore) the enter animation plays fine.

So if we want to fix this, we need to find the exact panel so that we can update the damage value everytime a player streams in the vehicle, but dont update the other panels that could have been damaged. However, since the tailwheel makes the enter animation bug, I don't think if it's worth it. Because that is trading one problem for another one that is actually a little worse. The first one is just cosmetice, the seconde one interferes with the gameplay.

The final commit of the code I used can still be found [here](https://github.com/WoutProvost/sa-mp-fixes/commits/master).
I also searched the **Bug List** thread in the **Bug Reports** forums and found these posts related to the bug:
- http://forum.sa-mp.com/showthread.php?p=2542919&highlight=tail#post2542919
- http://forum.sa-mp.com/showthread.php?p=1432867&highlight=tail#post1432867
- http://forum.sa-mp.com/showthread.php?p=1315038&highlight=tail#post1315038

**Comment by ziggi** [comment]
Streaming update time depends on stream_rate value from server.cfg, I think you should use this value + player ping + some reserve for getting better results.

P.S. Remove sample script from repository, you can add it in GitHub Gists or on something like this. And you should add space between **operator** and **(**:

``` Pawn
if (...)
```

After it I can merge this.

P.P.S. Did you test it for vehicles that do not streaming after creating? I think this may not work. If this not works then you have to use first call of OnVehicleStreamedIn for execution these operations.

**Comment by WoutProvost** [comment]
> Remove sample script from repository

Test script removed from repository. It can be found on [Pastebin](http://pastebin.com/1fg6f6cg) and on [GitHub Gists](https://gist.github.com/WoutProvost/cf82bc4fb3dfb98c23e5265c4c7dc8c1). Link in previous post updated.

> You should add space between operator and (

Added space like you mentioned to be conform with the coding conventions in the include.

> Streaming update time depends on stream_rate value from server.cfg, I think you should use this value + player ping + some reserve for getting better results.

My **stream_rate** was 1000 ms, which is the default. My **stream_distance** was 300.0, which is the default. My ping was 16 (local server, client on same machine). 6 standard bots and 2 FCNPC bots were connected to the server, other than that just me. Still got a peak value above 1500, so a reserve value of 1000 to catch the most extreme cases should suffice I reckon. The test were not performed on a completely bare gamemode though, can retest them if needed. But at least the testresults I have now, represent probably the average server script. However I don't know if many connected players will alter the results.

**player ping**
The current comitted script is operating with a single global timer hooked to the 3 create vehicle functions. I don't know if this timer is still needed though, since I probably have to use OnVehicleStreamIn anyway.

> Did you test it for vehicles that do not streaming after creating?

Yes, the Stuntplanes created in OnGameModeInit don't have a tailwheel when I join the server.

**Second test**
I also did a test (with just updating the damage status in OnVehicleStreamIn, did not include the fix with the timer) where I created a plane far away from my current player position, travelled to it and sometimes the plane had a tailwheel, sometimes it did not (pretty random). The code for the second test can be found [here](https://gist.github.com/WoutProvost/5c163cc0475dc64b3986655f6abfe149).

**Animation bug**
I have created a video to show what I mean by the animation bugging out when there is a tailwheel present: [click](https://www.youtube.com/watch?v=F-gLxsVIHi8&index=2&list=PLoh7sSsjdgnQczexBKaEte4mTg2N8B6H1).

So I don't think you should merge already, since there are still problems.

**Comment by Y-Less** [comment]
The broken animation looks like an incorrect damage status as well - the game thinks there is no door to open.

**Comment by WoutProvost** [comment]
Oh wow, completely forgot about this issue.

> The broken animation looks like an incorrect damage status as well - the game thinks there is no door to open.

Yes, just like the animation is different/shorter when a car door is not attached anymore.

Anyway, the solution is probably just updating the damage status when streaming in. However, since it creates the animation bug, I don't know if it's even worth it. The tail not appearing is just cosmetic, the animation being bugged is a lot uglier imo.

**Comment by Y-Less** [comment]
If you are updating the damage status for the wheel, you could try updating it for the door as well at the same time.  Fix both at once (maybe).

**Comment by WoutProvost** [comment]
Hadn't thought of that. Will try that when I get around to it.

**Comment by Y-Less** [comment]
I would, but I don't even have San Andreas installed right now.

**Comment by Y-Less** [comment]
That would require tracking the vehicle damage status though, maybe even just call "Get" then "Set" instantly in case the plane truly is damaged.

**Comment by WoutProvost** [comment]
So, I've done some tests and found the following:
* When using UpdateVehicleDamageStatus, panels has to be 0, doors has to be 0, lights has to be 0 and the value of tires doesn't matter, otherwise the tailwheel won't appear.
* It doesn't seem to matter what values u use in UpdateVehicleDamageStatus, it doesn't affect the plane's handling. A 1 for panels, does give permanent black smoke, but the handling remains unchanged.
* If you brake a flap or such on a plane, GetVehicleDamageStatus will still return 0 for panels, doors, lights and tires.
* Given points 2 and 3, this either means that SA-MP doesn't have an implementation for the damage status of planes, or the game stores the plane hanlding being affected in some other way and SA-MP just doesn't have a getter function for that yet. If the latter is the case, SA-MP is definitely able to create a getter function for that, since RepairVehicle fixes the plane's handling.
* Given point 4, does this mean that you can't programmatically set a plane's flap to break?
* When using UpdateVehicleDamageStatus on a stuntplane, with panels, doors, lights and tires all 0, OnVehicleDamageStatusUpdate will not be called, probably because of point 4.
* When using RepairVehicle on a stuntplane, OnVehicleDamageStatusUpdate will not be called, again, probably because of point 4.
* Since it seems that nothing can really be broken on a stuntplane and as a result the values remain 0, your method of instantly getting and setting does work, because it is essentially the same as just using 0's for every value.

I haven't tried anything with OnVehicleStreamIn yet, all this information was gathered by using commands.

**Comment by WoutProvost** [comment]
Just tested with OnVehicleStreamIn and with multiple clients. Updating the damage status there does indeed work. The solution is very simple:

	public OnVehicleStreamIn(vehicleid, forplayerid)
	{
		if(GetVehicleModel(vehicleid) == 513) {
			//Method 1
			new panels, doors, lights, tires;
			GetVehicleDamageStatus(vehicleid, panels, doors, lights, tires);
			UpdateVehicleDamageStatus(vehicleid, panels, doors, lights, tires);

			//Method 2
			UpdateVehicleDamageStatus(vehicleid, 0, 0, 0, 0);
		}
		return 1;
	}

However, given point 4 in my previous comment, that we can't get at the values of the flaps and such of planes, so probably also not the canopy. And given point 1, that the doors value has to be 0. We can't fix the animation problem I think.

That's my conclusion. It would be nice if someone else would have a look at it. Who knows that I'm just completely on the wrong track and we actually can get at the values of a plane's flaps and others.

**Comment by WoutProvost** [comment]
I watched a video on YT some time ago (can't remember which one) and apparently the health system does work differently for planes and helicopters. So the results I got with my experimentation, explained in the above posts, might be valid.

**Comment by rt-2** [comment]
Yes the system does work differently for normal vehicles+helicopters vs planes.

**Comment by WoutProvost** [comment]
I'm archiving this, since it is something that can only be fixed client side, or within SA-MP server side.
