### ISSUE TITLE
A couple of missing useful fixes

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/sa-mp-fixes#92]
Hi, I know a few ready-made implementations of important fixes, which unfortunately are not currently available in fixes.inc and it would be very nice if they were included.

1. Fix of "silent" teleport (when vehicle with its driver teleports somewhere at the same time you are trying to enter it as a driver): https://github.com/RogueDrifter/Silent-teleport-bugfix-inc-
2. Fix of GetTickCount function after 24 days server running: https://gist.github.com/ziggi/5d7d8dc42f54531feba7ae924c608e73

**Comment by Y-Less** [comment]
The first fix, maybe, if we can get permission. The second "fix" isn't a fix at all, it is excessive code to account for people misunderstanding wrap around numbers. There is literally nothing wrong with GetTickCount, but someone wrote that code pointlessly and now it refuses to die.

**Comment by RogueDrifter** [comment]
I don't mind that at all, gimme some time and I might submit a pull request. 
EDIT: Done.
