### ISSUE TITLE
SelectTextDraw + ShowPlayerDialog

### ISSUE THREAD

**Issue by ismoiliy98** [Open-GTO/sa-mp-fixes#96]
When some player is in the textdraw selection mode and if some dialog is displayed, the player can select textdraws above the layer of the dialog.

- [**Video (clickable)**](https://youtu.be/3HneFwC9lRU)
- [**Codes used in the video for testing (clickable)**](https://gist.github.com/Geebrox/5e32bd3496299102cdcedc0b2029fe3f)
- [**Fix (clickable)**](https://gist.github.com/Geebrox/82b2eafc4963c0acb3ba634c848a604f)

**Comment by Y-Less** [comment]
Is this a bug? It seems you have two things that are clickable shown at once, and they both continue to be usable. Why is hiding one more correct than leaving them both?

**Comment by ziggi** [comment]
Yeap, also developers can create interfaces with ShowPlayerDialog and SelectTextDraw for usage at the same time.

**Comment by IstuntmanI** [comment]
This is more like a problem: http://forum.sa-mp.com/showthread.php?t=644546

**Comment by ismoiliy98** [comment]
> Is this a bug?

I can't say that it is a bug. But this situation can cause problems and inconvenience for some developers.

> It seems you have two things that are clickable shown at once, and they both continue to be usable. Why is hiding one more correct than leaving them both?

Because as You can see in the video above, some dialogs can be escaped. Even I had some situations when players clicked dialogs' buttons and under that buttons were clickable textdraws, and the script processed both of them at the same time.

>Yeap, also developers can create interfaces with ShowPlayerDialog and SelectTextDraw for usage at the same time.

Ok, then they can skip this fix. As with other fixes, this fix can be skippable too. But I think there is very small part of the community who will use ShowPlayerDialog + SelectTextDraw simultaneously.

**Comment by Y-Less** [comment]
It seems to me the best solution is, if you don't want both showing at once, don't show both at once. If in your script you show a text draw then show a dialog, you can't then complain that there is both a text draw and a dialog showing. That's not what I'd call a bug - you explicitly programmed it! If you want to show a dialog without any text draws, hide any text draws you are already showing.

This really seems like a script issue more than a SA-MP issue - you asked for two things, it gave you two things...

**Comment by Daniel-Cortez** [comment]
> This really seems like a script issue more than a SA-MP issue - you asked for two things, **it gave you two things**...

More like "gave you one thing, then gave you another one but you dropped the first one - and that's when you noticed that for whatever reason you only have one hand and thus can't hold two things at once".

In all seriousness though, whether this is considered a bug or not, I think it would be great if fixes.inc remembered if textdraw selection mode was enabled when showing a dialog and restored it after player finished interaction with the dialog. Better have the fix here than having to redo or reapply a custom workaround for every gamemode/FS that suffers from this bug/feature.
